name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnotcurses-dev libncurses-dev libvterm-dev pkg-config
      - name: Build all configs
        run: make CFLAGS="-Wall -Wextra -O2 -Wno-clobbered -Werror"
      - name: Test the binaries run
        run: ./example --version
